reporter: xcode

included:
  - AvoidSoftinputExample/
  - ../../react-native-avoid-softinput/ios/

excluded:
  - Pods/

opt_in_rules:
  - anyobject_protocol
  - block_based_kvo
  - class_delegate_protocol
  - compiler_protocol_init
  - contains_over_first_not_nil
  - deployment_target
  - discarded_notification_center_observer
  - duplicate_enum_cases
  - duplicate_imports
  - dynamic_inline
  - empty_count
  - empty_parameters
  - empty_string
  - identical_operands
  - inert_defer
  - indentation_width
  - legacy_cggeometry_functions
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_nsgeometry_functions
  - legacy_random
  - no_fallthrough_only
  - no_space_in_method_call
  - nslocalizedstring_key
  - nsobject_prefer_isequal
  - operator_usage_whitespace
  - private_unit_test
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_set_access_control
  - redundant_void_return
  - strong_iboutlet
  - trailing_newline
  - trailing_semicolon
  - unneeded_break_in_switch
  - unused_capture_list
  - unused_control_flow_label
  - void_return
  - weak_delegate

  - array_init
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_range_nil_comparison
  - colon
  - comma
  - control_statement
  - empty_collection_literal
  - empty_parentheses_with_trailing_closure
  - flatmap_over_map_reduce
  - generic_type_name
  - identifier_name
  - implicitly_unwrapped_optional
  - leading_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - multiline_arguments
  - multiline_parameters
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters_brackets
  - nslocalizedstring_require_bundle
  - opening_brace
  - operator_whitespace
  - optional_enum_case_matching
  - orphaned_doc_comment
  - prefer_self_type_over_type_of_self
  - reduce_boolean
  - reduce_into
  - return_arrow_whitespace
  - statement_position
  - syntactic_sugar
  - trailing_whitespace
  - type_name
  - unused_import
  - unneeded_parentheses_in_closure_argument
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - yoda_condition
  - xctfail_message

type_name:
  min_length: 1
  max_length: 99

identifier_name:
  min_length: 1
  max_length: 99

disabled_rules:
  - attributes
  - closure_body_length
  - conditional_returns_on_newline
  - cyclomatic_complexity
  - discouraged_direct_init
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_enum_arguments
  - empty_xctest_method
  - explicit_enum_raw_value
  - explicit_self 
  - explicit_type_interface
  - fallthrough
  - fatal_error_message
  - file_header
  - file_length
  - file_name
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_default_parameter_at_end
  - function_parameter_count
  - implicit_return
  - joined_default_parameter
  - large_tuple
  - let_var_whitespace
  - multiline_function_chains
  - multiple_closures_with_trailing_closure
  - nesting
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - notification_center_detachment
  - number_separator
  - object_literal
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_over_fileprivate
  - prohibited_super_call
  - redundant_string_enum_value
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - static_operator
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - type_body_length
  - unavailable_function
  - untyped_error_in_catch
  - unused_closure_parameter
  - unused_optional_binding
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
