nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-postinstall.cjs
    spec: "https://raw.githubusercontent.com/gravitywelluk/yarn-plugin-postinstall/master/bundles/%40yarnpkg/plugin-postinstall.js"

postinstall: "yarn pods:mobile && yarn pods:fabricMobile"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
