name: React Native Avoid Softinput - Example App Bug
description: Report a bug inside example app
labels: [example app bug]
body:
  - type: textarea
    attributes:
      label: Environment
      description: |
        Provide environment on which the issue exists.
      value: |
        Library version: ???
        OS version: ??? <!-- e.g. iPhone 13, iOS 15.3.1 -->
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Affected platforms
      options:
        - label: "Android"
        - label: "iOS"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current behavior
      description: |
        Describe current behavior, add screenshots or videos, if it's affecting UI.
      placeholder: |
        Current behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: |
        Describe expected behavior.
      placeholder: |
        Expected behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
      description: |
        Add steps to reproduce bug inside example app.
      placeholder: |
        Steps to reproduce...
    validations:
      required: true
