name: React Native Avoid Softinput - Feature
description: Propose a feature in React Native Avoid Softinput
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Feature request
      description: |
        Describe feature request, why (and, if possible, how) it should be implemented
    validations:
      required: true
