export const ROUTES = {
  Home: 'Home' as const,
  FullScreenScrollView: 'FullScreenScrollView' as const,
  FullScreenView: 'FullScreenView' as const,
  BottomScrollViewWithFlex: 'BottomScrollViewWithFlex' as const,
  BottomScrollView: 'BottomScrollView' as const,
  ModalScrollView: 'ModalScrollView' as const,
  ModalView: 'ModalView' as const,
  FullScreenViewWithOffset: 'FullScreenViewWithOffset' as const,
  FullScreenScrollViewWithSingleInput: 'FullScreenScrollViewWithSingleInput' as const,
  // AppliedOffsetEvents: 'AppliedOffsetEvents' as const,
  CustomAnimationConfigModule: 'CustomAnimationConfigModule' as const,
  CustomAnimationConfigComponent: 'CustomAnimationConfigComponent' as const,
  Form: 'Form' as const,
  MultilineForm: 'MultilineForm' as const,
  TopScrollView: 'TopScrollView' as const,
  TopScrollViewWithFlex: 'TopScrollViewWithFlex' as const,
  HalfScrollView: 'HalfScrollView' as const,
  HalfScrollViewWithFlex: 'HalfScrollViewWithFlex' as const,
  NestedHorizontalScrollView: 'NestedHorizontalScrollView' as const,
  //
  ModuleExamples: 'ModuleExamples' as const,
  ModuleFullScreenExamples: 'ModuleFullScreenExamples' as const,
  ModuleScrollExamples: 'ModuleScrollExamples' as const,
  //
  ViewExamples: 'ViewExamples' as const,
  ViewFullScreenExamples: 'ViewFullScreenExamples' as const,
  ViewModalExamples: 'ViewModalExamples' as const,
};