export const ROUTES = Object.freeze({
  Home: 'Home',
  BottomSheet: 'BottomSheet',
  CustomAnimationConfigModule: 'CustomAnimationConfigModule',
  CustomAnimationConfigView: 'CustomAnimationConfigView',
  EnabledViewProp: 'EnabledViewProp',
  Form: 'Form',
  KeyboardType: 'KeyboardType',
  Modal: 'Modal',
  ModalFormSheet: 'ModalFormSheet',
  PasswordForm: 'PasswordForm',
  Reanimated: 'Reanimated',
  ScreensNativeModal: 'ScreensNativeModal',
  StickyFooter: 'StickyFooter',
});
