name: build-docs

on:
  pull_request:
    branches: [master]
    paths:
      - "docs/**"
      - "packages/react-native-avoid-softinput/**"
      - ".github/workflows/build-docs.yml"
  push:
    branches: [master]
    paths:
      - "docs/**"
      - "packages/react-native-avoid-softinput/**"
      - ".github/workflows/build-docs.yml"

jobs:
  checks:
    if: github.event_name != 'push'
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore node_modules from cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Test Build
        run: |
          yarn --cwd docs install --frozen-lockfile
          yarn --cwd docs build
  gh-release:
    if: github.event_name != 'pull_request'
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add key to allow access to repository
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat <<EOT >> ~/.ssh/config
          Host github.com
          HostName github.com
          IdentityFile ~/.ssh/id_rsa
          EOT
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore node_modules from cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
          CURRENT_BRANCH: master
          DEPLOYMENT_BRANCH: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "luigimario1913@gmail.com"
          git config --global user.name "Mateusz Mędrek"
          yarn --cwd docs install --frozen-lockfile
          yarn --cwd docs deploy
