name: lint-ios

on:
  pull_request:
    branches: [main]
    paths:
      - "packages/react-native-avoid-softinput/ios/**"
      - ".github/workflows/lint-ios.yml"

jobs:
  lint-ios:
    name: Lint ObjC
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
        - 'packages/react-native-avoid-softinput/ios'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          fetch-depth: 0

      - name: Setup JS
        uses: ./.github/actions/setup-js
        with:
          enable-cache: true

      - name: Run ClangFormat
        uses: jidicula/clang-format-action@654a770daa28443dd111d133e4083e21c1075674 #v4.18.0
        with:
          check-path: ${{ matrix.path }}
