name: lint-android

on:
  pull_request:
    branches: [master]
    paths:
      - "packages/mobile/android/**"
      - "packages/react-native-avoid-softinput/android/**"
      - ".github/workflows/lint-android.yml"

jobs:
  lint-android:
    name: Lint Kotlin/Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Spotless/Ktlint
        run: yarn lint:android
