name: lint-android

on:
  pull_request:
    branches: [master]
    paths:
      - "packages/mobile/android/**"
      - "packages/react-native-avoid-softinput/android/**"
      - ".github/workflows/lint-android.yml"

jobs:
  lint-android:
    name: Lint Kotlin/Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install modules
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"
          cache-dependency-path: "**/yarn.lock"
      - run: yarn
      - name: Spotless/Ktlint
        run: yarn lint:android
