name: Pre-release to NPM

on: 
  workflow_dispatch:

jobs:
  pre-release:
    uses: mateusz1913/react-native-avoid-softinput/.github/workflows/npm-release-template.yml@main
    with:
      pre_release: true
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
